version: "3.8"
services:
  db:
    image: 'postgres'
    restart: always
    env_file:
      - ./db.env
    volumes:
      - ./db:/var/lib/postgresql/
    ports:
      - "5432:5432"
  backend:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - ./logs:/app/logs
      - ./:/app
      - /app/node_modules
    env_file:
      - ./app.env
    depends_on:
      - db
